### ISSUE TITLE
Add Path to lightline on Update.sh

### ISSUE THREAD

**Issue by guillermorodriguez-wk** [pineapplegiant/spaceduck#1]
Hey first off love your work bro! Not enough kindness and love in the world these days, just wanted to start off with this.

But yeah, I ran the ./update.sh and it didn't move the lightline theme to the right place. I think you want to add this path in there:

`/Users/$USER/.local/share/nvim/plugged/lightline.vim/autoload/lightline/colorscheme`

**Comment by pineapplegiant** [comment]
Wow, bro, that's the nicest thing anyone has ever said to me. That means a lot!
I went ahead and threw that bad boy in there, thanks! :)
