### ISSUE TITLE
What is the name of the font in this screenshot in the README?

### ISSUE THREAD

**Issue by ceoshikhar** [pineapplegiant/spaceduck#17]
![image](https://user-images.githubusercontent.com/62669971/107117513-bd9a6380-68a0-11eb-849d-333d9a070b6a.png)

Great theme! Loved the font and want to make my setup look the same. Thanks

**Comment by pineapplegiant** [comment]
☺️ I’m delighted you like it! I am using “Fura mono” nerd font. It’s the patched Fira mono font so you can use icons. You can download it from the [nerd fonts repo here](https://github.com/ryanoasis/nerd-fonts/tree/master/patched-fonts/FiraMono). Apparently, if you like ligatures you can also use Fira code instead.

Thanks for chiming in. I’ll pin this when I get on my computer so others can see.

**Comment by ceoshikhar** [comment]
Thank you for such a quick reply! 😁
