### ISSUE TITLE
Colors not working

### ISSUE THREAD

**Issue by cristianpjensen** [pineapplegiant/spaceduck#18]
Hi, I'm new to vim and am trying to get your colorscheme to work in my terminal. I am using iTerm2. The colors don't seem to work for me though. I've tried everything I could find about colorschemes, but nothing seems to work. Below is a screenshot of what it looks like.

<img width="1082" alt="Screenshot 2021-02-18 at 02 39 45" src="https://user-images.githubusercontent.com/62624115/108293773-0e5d6680-7195-11eb-97f0-9413092a3f38.png">

Any help with this is appreciated.

**Comment by pineapplegiant** [comment]
Let me try to recreate the issue...are you using it inside of Tmux by any chance?

**Comment by pineapplegiant** [comment]
Hmm, from your screenshot it looks like it has something to to do with the `termguicolors` setting. I was playing with Vundle and everything seemed to download okay with the syntax from the vimrc that you've shown. 

Can you go ahead and run `:set termguicolors`? 

If it says `notermguicolors` then maybe the if-block in the readme isn't really working like I'd like it to. Setting it should hopefully fix the issue. Look at the images below for reference on what I mean.

**With NO termguicolors:**
<img width="932" alt="WithoutTermGuiClors" src="https://user-images.githubusercontent.com/32819563/108316589-53c06a80-717a-11eb-99a3-6e46564fa289.png">

**With Termguicolors on:**
<img width="932" alt="withTermGuiColors" src="https://user-images.githubusercontent.com/32819563/108316592-54f19780-717a-11eb-8215-3899a643318f.png">

**Comment by cristianpjensen** [comment]
Thank you for your reply. I looked further into it and it had something to do with my vim. I was using the vim that comes with macos, instead of the homebrew version. I am now using the homebrew version and everything seems to be working. I don't understand why, but maybe the macos version can't use termguicolors? I don't know.

**Comment by pineapplegiant** [comment]
Might be an older version of vim that doesn’t support the feature, yeah. 

Glad you were able to figure it out and thanks for sharing so others can learn from that.
