### ISSUE TITLE
Support for kitty

### ISSUE THREAD

**Issue by sureyeaah** [pineapplegiant/spaceduck#2]
It would be great if you could add support for kitty terminal. Thanks!

**Comment by pineapplegiant** [comment]
Looks like an easy lift, along with Alacritty. If you have the bandwidth feel free to port it! I'll get to it soon.

**Comment by fuadnafiz98** [comment]
I can port this to kitty and alacritty if  anyone not apporching

**Comment by pineapplegiant** [comment]
@fuadnafiz98 If you have the time that would be great! Let me know if you need help with the colors.

**Comment by fuadnafiz98** [comment]
@pineapplegiant  Sure, I would love to do that, I am experimenting with the colors and will report back to you if anything I need :)

**Comment by fuadnafiz98** [comment]
Currently, this is the 16 color palette, I need either a new blue or a new cyan, the rest of the colors seems ok to me. 

![image](https://user-images.githubusercontent.com/43469396/102086154-d149c080-3e41-11eb-8816-2310061638f0.png)

**Comment by pineapplegiant** [comment]
@fuadnafiz98 I know it looks crazy, but this is how I have my iTerm setup, maybe it helps.

<img width="550" alt="Screen Shot 2020-12-14 at 12 29 04 PM" src="https://user-images.githubusercontent.com/32819563/102132114-076a4e80-3e08-11eb-971d-8626d1d8cb51.png">

**Comment by fuadnafiz98** [comment]
Thanks, But the **yellow** and **magenta** is confused me a bit, so I swapped them. 
Anyway, I am making a PR with two versions ( one like you created with Item2 and my version).

**Comment by pineapplegiant** [comment]
@sureyeaah you can find the [kitty theme here!](https://github.com/pineapplegiant/spaceduck/blob/main/term/spaceduck.conf) let me know if there's any issues.
