### ISSUE TITLE
Incorrect Colors for Vim

### ISSUE THREAD

**Issue by petrovskidavid21** [pineapplegiant/spaceduck#23]
After installing this plugin for vim, I noticed that some of the colors are not showing up like they should, going off by the screenshots posted in the repo. I also downloaded the VSCode version to compare it with my Vim and I saw a difference.

Here is a screenshot of how my vim looks (keep in mind for the color of the comments I modified it to be gray, but that is the only modification I did).
![Screen Shot 2021-03-30 at 12 28 17 PM](https://user-images.githubusercontent.com/50383916/113030650-73708880-9153-11eb-97e6-f64461050120.png)

And something that is even more weird is that when I add the 
`    if exists('+termguicolors')
      let &t_8f = "\<Esc>[38;2;%lu;%lu;%lum"
      let &t_8b = "\<Esc>[48;2;%lu;%lu;%lum"
      set termguicolors
    endif`
code to my .vimrc the colors change even more. Here is a screenshot to show what I mean.
![Screen Shot 2021-03-30 at 12 30 26 PM](https://user-images.githubusercontent.com/50383916/113030971-c34f4f80-9153-11eb-9e80-53076ea2bb9a.png)

This might be some user error from my part, so any help will be appreciated.

Also I am using "VIM - Vi IMproved" version 8.2.2375 if that helps.

**Comment by petrovskidavid21** [comment]
I am using the Terminal App on Mac. Thats what I was thinking but I wasn't sure. Any suggestions?

**Comment by pineapplegiant** [comment]
Ahh yeah the default terminal app last I checked doesn’t support “true color” it’s so dumb 😔. I have a link to it in the readme that talks more in depth about it:

https://gist.github.com/XVilka/8346728

It’s why I switched to iTerm and then recently to alacritty. I’ll get around to making an optimized 256 color scheme though. Let me know if that fixes it?

**Comment by petrovskidavid21** [comment]
Perfect! Thank you so much, that makes a lot more sense now. I actually just got it to work with iTerm and I'm loving it. Thanks for the help again.

**Comment by pineapplegiant** [comment]
Yay! Thanks for submitting an issue feel free to post any other pictures that seem off.

**Comment by vaileamon** [comment]
I have the exact same issue, but using Xterm2, with
```
if exists('+termguicolors')
      let &t_8f = "\<Esc>[38;2;%lu;%lu;%lum"
      let &t_8b = "\<Esc>[48;2;%lu;%lu;%lum"
      set termguicolors
    endif
```
correctly set. 
Xterms seems to handle colors correctly as i use the same colorscheme for xterm's colors and that works like a charm.
I try kind of everything I could think of, do you guys have an idea ?
