### ISSUE TITLE
Unfocus tab too dark

### ISSUE THREAD

**Issue by Eliot00** [pineapplegiant/spaceduck#25]
Not sure if it’s a bug, but it looks too dark

<img width="1261" alt="截屏" src="https://user-images.githubusercontent.com/18375468/113377335-9b0b5f00-93a6-11eb-8629-e8e018965183.png">

**Comment by pineapplegiant** [comment]
Is this Airline? Yeah that looks busted lol. 

I’ll fix it this weekend. I haven’t tested Airline just light line.

**Comment by Eliot00** [comment]
> Is this Airline? Yeah that looks busted lol.
> 
> I’ll fix it this weekend. I haven’t tested Airline just light line.

Yes it's Airline, and thanks for your nice work on the theme.

**Comment by jinh0** [comment]
I've had this same issue, which is when you have `let g:airline#extensions#tabline#enabled = 1` on, which shows buffers as well as tabs.

Normally, spaceduck looks great as usual with that setting off:
<img width="1647" alt="Screen Shot 2021-04-02 at 6 17 47 PM" src="https://user-images.githubusercontent.com/40512164/113402490-0aea0b80-93e0-11eb-8bbb-af9cc57021fb.png">

But for some reason with `let g:airline#extensions#tabline#enabled = 1`, the colors are messed up, just like yours:
<img width="1653" alt="Screen Shot 2021-04-02 at 6 18 20 PM" src="https://user-images.githubusercontent.com/40512164/113402617-3ff65e00-93e0-11eb-9de2-3201521ca78e.png">

 I might  look into fixing these colors myself this evening. I'll let you know if I make some progress.

**Comment by jinh0** [comment]
UPDATE: 
<img width="1652" alt="Screen Shot 2021-04-02 at 7 16 26 PM" src="https://user-images.githubusercontent.com/40512164/113407281-ef82fe80-93e7-11eb-842c-cc656364c2c3.png">

When changes have been made to the file:
<img width="1647" alt="Screen Shot 2021-04-02 at 7 13 27 PM" src="https://user-images.githubusercontent.com/40512164/113407171-bfd3f680-93e7-11eb-90b8-cdc23b9b8e0f.png">

I added this to spaceduck/autoload/airline/themes/spaceduck.vim
```
" tabline colors
let s:tab_background = [ "#ecf0c1", "#0f111b", 255, 233]
let s:selected_tab = [ "#000000", "#686f9a", 237, 60 ]
let s:background_tab = [ "#686f9a", "#30365F", 146, 0 ]

" reference airline-tabline-hlgroups
let g:airline#themes#spaceduck#palette.tabline = {
  \ "airline_tab": s:background_tab,
  \ "airline_tab_right": s:background_tab,
  \ "airline_tabsel": s:selected_tab,
  \ "airline_tabsel_right": s:selected_tab,
  \ "airline_tabfill": s:tab_background,
  \ }
```

Let me know what you guys think. I was following the Airline colors used, but I'd appreciate your feedback.

**Comment by Eliot00** [comment]
> UPDATE:
> I added this to spaceduck/autoload/airline/themes/spaceduck.vim
> 
> ```
> " tabline colors
> let s:tab_background = [ "#ecf0c1", "#0f111b", 255, 233]
> let s:selected_tab = [ "#000000", "#686f9a", 237, 60 ]
> let s:background_tab = [ "#686f9a", "#30365F", 146, 0 ]
> 
> " reference airline-tabline-hlgroups
> let g:airline#themes#spaceduck#palette.tabline = {
>   \ "airline_tab": s:background_tab,
>   \ "airline_tab_right": s:background_tab,
>   \ "airline_tabsel": s:selected_tab,
>   \ "airline_tabsel_right": s:selected_tab,
>   \ "airline_tabfill": s:tab_background,
>   \ }
> ```
> 
> <img alt="Screen Shot 2021-04-02 at 7 16 26 PM" width="1652" src="https://user-images.githubusercontent.com/40512164/113407281-ef82fe80-93e7-11eb-842c-cc656364c2c3.png">
> 
> When changes have been made to the file:
> <img alt="Screen Shot 2021-04-02 at 7 13 27 PM" width="1647" src="https://user-images.githubusercontent.com/40512164/113407171-bfd3f680-93e7-11eb-90b8-cdc23b9b8e0f.png">
> 
> Let me know what you guys think. I was following the Airline colors used, but I'd appreciate your feedback.

I like this, thank you.

**Comment by pineapplegiant** [comment]
Thanks for this!

Yeah I think this might be a bug with [these lines in the raw colorscheme](https://github.com/pineapplegiant/spaceduck/blob/836a90f614aefac45149d7b893e116bf9c7a59ee/colors/spaceduck.vim#L71-L73), let me play with it before adding this in the airlines theme.

I switched to using bar bar and have this for my tabline, so hopefully I can recreate, as I like the smooth blended look into the background. But the tabline you have looks very bright and good as well.
![Screen Shot 2021-04-04 at 7 00 14 PM](https://user-images.githubusercontent.com/32819563/113526622-fe98b680-9577-11eb-9f40-646ae9bd7414.png)

**Comment by jinh0** [comment]
I think your smooth blended look is better. The original colors I used was because it matches the the bottom Airline status bar. 

So I tried using the barbar colors from your screenshot for the Airline tabs, but it doesn't look as pretty.

This is how the barbar look translates:
<img width="1220" alt="Screen Shot 2021-04-08 at 11 15 21 PM" src="https://user-images.githubusercontent.com/40512164/114042551-7e988680-98c0-11eb-9fe0-a8d64eb23361.png">

This is probably because barbar makes the tabs follow a modern GUI look while Airline tabs are simply functional (also separates buffers and tabs).

I think the Airline tabs look better with a purple highlight:
<img width="1673" alt="Screen Shot 2021-04-08 at 11 21 15 PM" src="https://user-images.githubusercontent.com/40512164/114043292-20b86e80-98c1-11eb-91ad-5c6a2f906e0d.png">

I also made it so that when the file is modified, the tab is that beautiful spaceduck green:
<img width="1676" alt="Screen Shot 2021-04-08 at 11 21 40 PM" src="https://user-images.githubusercontent.com/40512164/114043352-2dd55d80-98c1-11eb-896e-ee7c347fce5c.png">

(I can't stress enough how much I love the spaceduck colors.)

Let me know what you think.

**Comment by pineapplegiant** [comment]
This looks perfect oh my goodness! Apologies for taking so long on this.
Yes I would very much like this in the theme!
I can do it or if you prefer to submit a PR, for recognition I'll gladly accept it. To make these changes, you'd want to edit the `/spaceduck/blob/main/estilo/syntax/base.yml` along with the base spaceduck file if you don't want to install the estilo dependency locally.

**Comment by jinh0** [comment]
The Airline status bar and tab line both have been fixed and are ready for release. Currently, it is in the dev branch.

Thanks for reporting the issue!
