### ISSUE TITLE
Missing highlighting in TypeScript

### ISSUE THREAD

**Issue by Tomburgs** [pineapplegiant/spaceduck#3]
Hey, I love the color scheme, but there are some issues with it when working with TypeScript / TypeScript React.

Here's some of the issues I've encountered:
- Keywords such as `const` and `typeof` don't get highlighted (default foreground color).
- Function keyword is highlighted in the same color as the name of the function.
- Function return type doesn't always get highlighted (JSX.Element in the screenshot).

Here's screenshots for comparison

**Default**
![default](https://i.imgur.com/3WYs63l.png)

**Spaceduck**
![spaceduck](https://i.imgur.com/zGnF2F1.png)

It seems like the `typescriptVariable` / `typescriptType` / etc Vim values need to be linked to the correct definitions, however, I'm not sure how this works with the Estilo workflow.

I'm also concerned about the color on comments or HTML brackets, as they are quite dark and a bit difficult to read / see.
Perhaps there's something that can be done about this?

**Comment by pineapplegiant** [comment]
Oof yeah that is ugly. 

Good find and these screenshots are great! I was able to recreate the error. I'll try to get this done in the next couple days as I need to standardize where colors go more consistently. Just curious, are you using a specific syntax plugin by any chance? Thanks again.

**Comment by Tomburgs** [comment]
> Just curious, are you using a specific syntax plugin by any chance? Thanks again.

I do have [vim-polyglot](https://github.com/sheerun/vim-polyglot) plugin installed which uses [yats.vim](https://github.com/HerringtonDarkholme/yats.vim), however it's now the default TypeScript highlighting in [Vim](https://github.com/vim/vim/blob/master/runtime/syntax/typescriptcommon.vim) & [NeoVim](https://github.com/neovim/neovim/blob/master/runtime/syntax/typescriptcommon.vim), so there shouldn't be any issues without it.

**Comment by pineapplegiant** [comment]
@Tomburgs Just updated the branch with another commit hopefully that fixes the Typescript issue. (I think there's too much pink now), but go ahead and give that a try. I just updated the README with all of the locations of the colors too.

**Comment by pineapplegiant** [comment]
<img width="832" alt="Screen Shot 2020-12-15 at 5 03 02 PM" src="https://user-images.githubusercontent.com/32819563/102291374-d10bfc80-3ef7-11eb-8922-ea13e4a46bf1.png">

Might change the pink braces. But I'm gonna close this for now!
