### ISSUE TITLE
Spaceduck theme for lightline.vim

### ISSUE THREAD

**Issue by jinh0** [pineapplegiant/spaceduck#37]
I recently ditched [vim-airline](https://github.com/vim-airline/vim-airline) due to its utter slowness for [lightline.vim](https://github.com/itchyny/lightline.vim) but there's no current spaceduck theme for it.

If anyone can make one for lightline, I'll immediately merge it with the `dev` branch.

**Comment by pineapplegiant** [comment]
bruh i made one

**Comment by pineapplegiant** [comment]
@jinh0 is drunk watch out https://github.com/pineapplegiant/spaceduck/blob/main/autoload/lightline/colorscheme/spaceduck.vim

**Comment by jinh0** [comment]
<img width="1635" alt="Screen Shot 2021-05-26 at 10 12 40 AM" src="https://user-images.githubusercontent.com/40512164/119588034-e8d29f80-be0a-11eb-816b-d4395a5fbb3b.png">
Looks terrible. Requires improvement. It should look similar to my airline theme.
