### ISSUE TITLE
enhancement: Vim Markdown syntax highlighting

### ISSUE THREAD

**Issue by bigpick** [pineapplegiant/spaceduck#48]
# Info
Right now, the default highlighting that comes with the vim plug doesn't do a great job doing the markdown (`.md`, for example) type files.

For reference, here is what we ended up going with (for now) for the atom syntax markdown:

![](https://user-images.githubusercontent.com/9803299/121198737-600f2700-c840-11eb-9556-2f148ede1e42.png)

---

# Currently Shipped w/vim plug

![Screen Shot 2021-06-09 at 5 21 09 PM](https://user-images.githubusercontent.com/9803299/121431204-1b21e800-c947-11eb-8392-ebba9ff91dbd.png)

# Local vim updates
![Screen Shot 2021-06-09 at 5 15 01 PM](https://user-images.githubusercontent.com/9803299/121430779-84552b80-c946-11eb-823e-e761fdacc285.png)

---

I can open a PR against the dev branch, if interested

**Comment by bigpick** [comment]
... for reference: https://github.com/pineapplegiant/spaceduck/compare/dev...bigpick:vim-readme-syntax-updates-1?expand=1

**Comment by TeoDev1611** [comment]
This issue could be closed because the pull request are merged 🤔 ?
