### ISSUE TITLE
Fix airline text color for inactive splits 

### ISSUE THREAD

**Issue by jclsn** [pineapplegiant/spaceduck#57]
The text of my inactive splits is too dark

![grafik](https://user-images.githubusercontent.com/19779511/138843039-2f92103f-4a5d-45cd-92f9-1797639d94c3.png)

I could fix it by changing

```
let s:inactive1 = [ "#1b1c36", "#16172d", 234, 234 ]
let s:inactive2 = [ "#1b1c36", "#16172d", 234, 234 ]
let s:inactive3 = [ "#1b1c36", "#16172d", 234, 234 ]
```

to 

```
let s:inactive1 = [ "#3b3c56", "#16172d", 234, 234 ]
let s:inactive2 = [ "#3b3c56", "#16172d", 234, 234 ]
let s:inactive3 = [ "#3b3c56", "#16172d", 234, 234 ]
```
Not sure if this is a Vim problem. Are the colors right in Neovim?

**Comment by jinh0** [comment]
It's been fixed in the `dev` branch for a while now. 

In fact, I'd recommend you use the `dev` branch until all the changes get pushed to the `main` branch.

**Comment by jclsn** [comment]
Had it fixed for myself anyway. Was just wondering why no one had reacted.

**Comment by pineapplegiant** [comment]
@jclsn because I’m a goof and totally forgot. I switched gears to working on the VScode theme since the editing process was easier. Hoping to get those updates here and just maintain the neovim/lua theme version thereafter. 

Anyway I appreciate you, thanks for following up

**Comment by jclsn** [comment]
Alright, hoping to see this merged. It's the first color theme I have stayed on for half a year now. That says a lot.

**Comment by pineapplegiant** [comment]
I know good color schemes are hard to come by. That means a lot. @jinh0 knows a lot of other good ones too. We’ll have to keep & share a list of other ones we like.

**Comment by jinh0** [comment]
Sadly nothing beats spaceduck, though we need to work on Treesitter support that looks nice for TypeScript :(
