### ISSUE TITLE
Cannot allocate color 0 error

### ISSUE THREAD

**Issue by excalios** [pineapplegiant/spaceduck#8]
I got this error everytime I try opening a file:
Error detected while processing /.vim/plugged/coc.nvim/plugin/coc.vim[458]..function <SNR>22_Hi[49]..<SNR>22_AddAnsiGroups:
line   18:
E254: Cannot allocate color 0
E254: Cannot allocate color 0

This only happens with this colorscheme using other colorscheme doesn't show the error

**Comment by pineapplegiant** [comment]
Hmmm. Not sure, looks like an issue with COC.

Can you tell me what terminal you're using? 
What does `echo $TERM` return?

**Comment by excalios** [comment]
I use kitty echo $TERM would return xterm-kitty and this is on fedora workstation 32.

I'm still unsure of the problem this happen when using vim. I just switched to neovim and haven't had the warning at all.

**Comment by anirudhsundar** [comment]
I'm facing the same error. I work on a remote machine and just have putty setup with truecolor support and it works fine for all other themes. My output for `echo $TERM` is `xterm-256color`. I'm still quite new to vimscript and have no clue how to debug this issue, so any help would be great.

**Comment by pineapplegiant** [comment]
Seems like the new estilo version is all kinds of messed up. Discovered the [Rigel colorscheme was having a similar issue](https://github.com/Rigellute/rigel/issues/10). I think the last commit should fix this!
